CREATE TABLE EXPRESSIONS(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    expressions_text VARCHAR NOT NULL,
    result_text VARCHAR,
    creat_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
